name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpdfium-dev

    - name: Build Native
      run: |
        make clean
        CFLAGS="-Wall -std=c17 -I/usr/include/pdfium" LDFLAGS="-lpdfium" make all

    - name: Run Tests
      run: |
        make test
        ./bin/pdf_handler tests/test.pdf tests/processed_test.pdf "INSPIRE 3" "INSPIRE 3 DMXY"

  build-wasm:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12

    - name: Build WebAssembly
      run: |
        make -f wasm.mk clean
        make -f wasm.mk

    - name: Verify WebAssembly Output
      run: |
        if [ ! -f "wasm/pdf_handler.js" ] || [ ! -f "wasm/pdf_handler.wasm" ]; then
          echo "WebAssembly build failed - output files missing"
          exit 1
        fi
