name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update

    - name: Verify PDFium library
      run: |
        ls -l lib/pdfium/lib/
        ls -l lib/pdfium/include/

    - name: Build Native
      run: |
        # Create symbolic link for libpdfium
        mkdir -p lib
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          ln -s $(pwd)/lib/pdfium/lib/libpdfium.a lib/libpdfium.a
        else
          ln -s $(pwd)/lib/pdfium/lib/libpdfium.a lib/libpdfium.a
        fi
        make clean all

    - name: Run Tests
      run: |
        make test
        ./bin/pdf_handler tests/test.pdf tests/processed_test.pdf "INSPIRE 3" "INSPIRE 3 DMXY"

  build-wasm:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12

    - name: Verify PDFium WebAssembly library
      run: |
        ls -l lib/pdfium/lib/
        ls -l lib/pdfium/include/

    - name: Build WebAssembly
      run: |
        make -f wasm.mk clean
        make -f wasm.mk

    - name: Verify WebAssembly Output
      run: |
        if [ ! -f "wasm/pdf_handler.js" ] || [ ! -f "wasm/pdf_handler.wasm" ]; then
          echo "WebAssembly build failed - output files missing"
          exit 1
        fi
