name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Download PDFium for Linux
      run: |
        mkdir -p temp_download
        cd temp_download
        wget https://github.com/bblanchon/pdfium-binaries/releases/download/chromium%2F5826/pdfium-linux-x64.tgz
        tar xzf pdfium-linux-x64.tgz
        sudo mkdir -p /usr/local/include/pdfium
        sudo cp -r include/* /usr/local/include/pdfium/
        sudo cp lib/libpdfium.so /usr/local/lib/
        sudo ldconfig
        cd ..
        rm -rf temp_download

    - name: Build Native
      run: |
        make clean
        CFLAGS="-Wall -std=c17 -I/usr/local/include" LDFLAGS="-L/usr/local/lib -lpdfium" make all

    - name: Run Tests
      run: |
        make test
        ./bin/pdf_handler tests/test.pdf tests/processed_test.pdf "INSPIRE 3" "INSPIRE 3 DMXY"

  build-wasm:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12

    - name: Build WebAssembly
      run: |
        make -f wasm.mk clean
        make -f wasm.mk

    - name: Verify WebAssembly Output
      run: |
        if [ ! -f "wasm/pdf_handler.js" ] || [ ! -f "wasm/pdf_handler.wasm" ]; then
          echo "WebAssembly build failed - output files missing"
          exit 1
        fi
